name: TruffleHog
on:
  pull_request:
  push: { branches: ["main"] }
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: trufflesecurity/trufflehog@v3.82.8
        with:
          extra_args: --only-verified --fail
